version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    container_name: rabbit_mq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_ERLANG_COOKIE=cookie
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER : root
    ports:
      - 5432:5432 
