version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    container_name: rabbit_mq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_ERLANG_COOKIE=cookie
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER : root
    ports:
      - 5432:5432 
  users-service:
    container_name: users-service
    build: 
      ./Users
    ports:
      - "5000:5000"
      - "50051:50051"
    environment:
      WAIT_HOSTS: rabbitmq:5672,db:5432
  product-service:
    container_name: product-service
    build: 
      ./Products
    ports:
      - "5100:5100"
      - "50052:50052"
    environment:
      WAIT_HOSTS: rabbitmq:5672,db:5432
  
