"""migration V1 .

Revision ID: 516e36a5967b
Revises: 
Create Date: 2021-04-05 17:55:20.182904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516e36a5967b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
