"""migration V2.

Revision ID: 90c4233f5fe8
Revises: d57d4649058e
Create Date: 2021-04-21 20:38:16.730443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c4233f5fe8'
down_revision = 'd57d4649058e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance', sa.Integer(), nullable=True))
    op.drop_column('user', 'cashBackBalance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cashBackBalance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'balance')
    # ### end Alembic commands ###
