"""migration V2.

Revision ID: d57d4649058e
Revises: 1d745e6289ed
Create Date: 2021-04-20 22:37:03.516566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57d4649058e'
down_revision = '1d745e6289ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ordersCount', sa.Integer(), nullable=True))
    op.drop_column('user', 'orderCount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('orderCount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'ordersCount')
    # ### end Alembic commands ###
