"""migration V3.

Revision ID: 168cb2b8342d
Revises: 373933438e9f
Create Date: 2021-04-22 20:29:39.260503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168cb2b8342d'
down_revision = '373933438e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
