"""migration V1.

Revision ID: 373933438e9f
Revises: 
Create Date: 2021-04-20 22:59:18.069847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373933438e9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('totalPrice', sa.Integer(), nullable=False),
    sa.Column('totalQuantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
