"""migration V4.

Revision ID: c6389c9f9302
Revises: 168cb2b8342d
Create Date: 2021-04-22 21:53:14.457398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6389c9f9302'
down_revision = '168cb2b8342d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'productId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'totalPrice',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'totalQuantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'totalQuantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'totalPrice',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'productId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
